### ISSUE TITLE
Failed differential analysis

### ISSUE THREAD

**Issue by kimaguresilvia** [MayurDivate/GUAVA#28]
Dear Dr Divate,
I am new with GUAVA-1. I got access to atac-seq data  from a consortium (human brain samples). I have BAM aligned read data files and narrow peaks files for each subject, but when I run a differential analysis I get this error in few seconds:

GUAVA version 1
GLib-GIO-Message: 12:28:06.057: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!
		samtools:	Working!
/home/sudouser/Documenti/CMCataqDIFF_GUAVA_Differental_analysis
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.DocumentHelper (file:/home/sudouser/GUAVA-1/lib/poi-ooxml-3.16-beta2.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.DocumentHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
---------- Create read count matrix ----------
B100T1.narrowPeak == 24528
B101T1.narrowPeak == 26499
B103T1.narrowPeak == 1480
B104T1.narrowPeak == 3939
---------- Run DESeq2 code ----------
Error in the differential analysis step
Error occured, analysis stopped

What should I do? 
Thank you.

**Comment by lailamargaret** [comment]
I am having the same issue. The Log File reads:

`Error in [<-.data.frame(*tmp*, d2res$log2FoldChange <= (-1 * fcCutoff) &  :
  missing values are not allowed in subscripted assignments of data frames
Calls: [<- -> [<-.data.frame
Execution halted`

**Comment by MayurDivate** [comment]
Dear @kimaguresilvia & @lailamargaret,

I need to look at log file to understand this issue.
can both of you please share the log file with me ?

Thanks,
Mayur

**Comment by lailamargaret** [comment]
Hello!

Please find the log file attached. Thanks.

[GUAVA_error_log.txt](https://github.com/MayurDivate/GUAVA/files/3649339/GUAVA_error_log.txt)

**Comment by kimaguresilvia** [comment]
[Diff_analysis_error.txt](https://github.com/MayurDivate/GUAVA/files/3651516/Diff_analysis_error.txt)
Here is mine.
Thank you very much for your help!

Silvia

**Comment by MayurDivate** [comment]
Hi Silvia,

This is an issue of R installation.
This [link](https://github.com/conda-forge/rpy2-feedstock/issues/1) may help you to the issue.

Mayur

**Comment by MayurDivate** [comment]
Dear @lailamargaret,

I just figured out what could be the possible issue. 
In order to solve that I will have to update GUAVA. 
Also, I will need your help in testing the update using your data.   

I will share the update as soon as with you and instructions to test it. 

Thanks,
Mayur

**Comment by ishwariyavenkatesh** [comment]
Hi Divate,
Thanks for a cool package! I'm attempting to run diffATAC function of GUAVA and as soon as I start it, it halts due to an error - 
#######################################################
# Project summary 
# Name of the project:	diffATAC_P0vsEA
# Genome build:	mm10
# Pvalue:	0.05
# Foldchange:	2.0
# Upstream:	3000
# Downstream:	300
# Input files
# Control REP I bam:	EA1.bam
# Control REP II bam:	EA2.bam
# Treatment REP I bam:	P0_rep1_R1.merged.nodup.bam
# Treatment REP II bam:	P0_rep2_R1.merged.nodup.bam
# Control REP I NarrowPeak:	EA1_fcortex_peak.NarrowPeak
# Control REP II narrowPeak:	EA2_fcortex_peaks.narrowPeak
# Treatment REP II narrowPeak:	P0_rep2_R1.merged.nodup.tn5.pval0.01.300K.bfilt.narrowPeak
# Treatment REP I narrowPeak:	P0_rep1_R1.merged.nodup.tn5.pval0.01.300K.bfilt.narrowPeak
#######################################################

--------- DESeq2 ---------
-------1-----------------------

------------------------------
_______2_______________________
dyld: Library not loaded: @rpath/libicuuc.54.dylib
  Referenced from: /Users/ish/miniconda2/lib/R/lib/libR.dylib
  Reason: image not found

______________________________
Help?

**Comment by ishwariyavenkatesh** [comment]
[P0_rep1_R1_log.txt](https://github.com/MayurDivate/GUAVA/files/3735761/P0_rep1_R1_log.txt)

**Comment by MayurDivate** [comment]
Hi ishwariya,

Sorry I did not see your message.  

This was a Mac lib boost issue.
Use this link [stackoverflow](https://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-found) unless you have already solved it. 

Thank you for using GUAVA !

Mayur

**Comment by ccmeth** [comment]
> Dear @lailamargaret,
> 
> I just figured out what could be the possible issue. In order to solve that I will have to update GUAVA. Also, I will need your help in testing the update using your data.
> 
> I will share the update as soon as with you and instructions to test it.
> 
> Thanks, Mayur

Hi, I used the latest version of GUAVA (1.0.1) and also met with such an issue, and I thought maybe the NA values resulted in the problems.
